export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

// ARTWORK
export const CREATE_ARTWORK = 'CREATE_ARTWORK';
export const GET_USER_ARTWORKS = 'GET_USER_ARTWORKS';
export const CLEAR_USER_ARTWORKS = 'CLEAR_USER_ARTWORKS';
export const DELETE_ARTWORK = 'DELETE_ARTWORK';
export const GET_ARTWORK = 'GET_ARTWORK';
export const CLEAR_ARTWORK = 'CLEAR_ARTWORK';
